### PR TITLE
Improving the spelling, formatting and contents of the README.md

### PR DESCRIPTION
**Pull request by Samuil1337**
Hello zhaodice,
I hope you are doing well. I took the liberty of fixing a few spelling and grammar mistakes in the readme. I also added a description of the project that I felt was missing.
It would be great if you pinned issue #48 instead of mentioning it in the readme, because it feels a little out of place. Especially because this patch shouldn't interfere with any GPU drivers.

### CODE REVIEW

**Comment by Samuil1337** [comment]
I also wanted to ask what the qemu:commandline section does. It looks like it is setting the manufacturers of the virtual hardware, but how exactly?

**Comment by Samuil1337** [comment]
My Libvirt config is in a separate file in a separate folder, so don't worry; I didn't override anything!

**Comment by zhaodice** [comment]
> qemu:commandline

Sounds good! I am not a English native speaker , it is very appriciated you can provide your improved texts.
`qemu:commandline` can add some parameter to executable `qemu-system-x86_64`, to enable some hardward Spoofing Features.

it you have no more problem, feel free to tell me so that I can do merge now.

**Comment by Samuil1337** [comment]
Yup, everything's ready to go. Thanks for the explanation!

**Pull request merged**
